export const GUEST_SESSION_TTL_DAYS = 7;

export const GUEST_SESSION_EXPIRED_CODE = 'GUEST_SESSION_EXPIRED';

export const GUEST_FEATURE_RESTRICTED_CODE = 'GUEST_FEATURE_RESTRICTED';

export const GUEST_DEVICE_SESSION_EXISTS_CODE = 'GUEST_DEVICE_SESSION_EXISTS';
